### PR TITLE
Replay functionality

### PR DESCRIPTION
**Pull request by gabek**
## Currently

- Only working with local storage.
- Functionality is hard coded to be enabled, there's no CLI flag yet.
- Only working with entire streams (beginning to end), windowing (clips) is not yet added.
- Playlists are generated on the fly each time. They are not cached or saved. Based on performance and feature preference, these playlists can be persisted. 

## Details

- /api/replays returns a list of all the streams that are replayable.

URLs are generated as so:

-  /replay/_streamId_ for master playlists.
- /replay/_streamId_/_configurationId_ for media playlists.

## Next steps

- Add support for windowed clips.
- Add support for S3 storage for all this functionality.
- Add error handling around if we have records for replayable content, but the files don't actually exist.

## Testing in progress stream

1. Start a live stream with this branch.
2. Visit http://localhost:8080/api/replays
3. Note the "manifest " path.
4. Put the manifest url in your livestreaming video player of choice.
5. Play it. It will be treated as an updating (event) style stream.

## Testing completed streams

1. Stop the live stream.
2. Visit http://localhost:8080/api/replays
3. Notice this stream is no longer in progress.
4. Put the manifest url in your livestreaming video player of choice.
5. Play it. It will be treated as a static (VOD) stream and will not update.

---
Thoughts:

- At launch all streams should be marked as no longer live. If somebody killed Owncast while a stream was live the `endTime` would never get set, leaving it to be infinitely "live".

### CODE REVIEW

**Comment by Fyb3roptik** [comment]
Looking good so far! I will pour through this tonight

**Comment by gabek** [comment]
## Clips

- Follow the instructions above to have a replay of a stream.
- Get the `streamId` you want to create a clip from.
- Determine the start and end points, in seconds, for this clip, relative to the beginning of the stream.
- Use the clip create API to create the clip as a JSON payload to `/api/clip` with `streamId`, `clipTitle`, `relativeStartTimeSeconds` and `relativeEndTimeSeconds`
```
http http://localhost:8080/api/clip streamId="oYk3sL6Vg" clipTitle="Test clip 5" relativeStartTimeSeconds:=10 relativeEndTimeSeconds:=17
```

image

- List all clips with the clips api `/api/clips`.
image

- Fetch a single clip with `/clip/{clipId}`.
- It will return back a HLS master playlist that is playable.

image

**Comment by gabek** [comment]
TODOs next, now that the core work is testable

- [x] Add support for object storage
- [x] Fix the thumbnail generator not looking in the updated locations
- [x] Auto-complete streams without an end time at launch.
- [x] CLI flag

**Review by Fyb3roptik — COMMENTED** [review]
Looks good so far! That was a long read through! haha

**Comment by gabek** [comment]
Going forward, you'll have to supply the `--enableReplayFeatures` flag at launch.

@Fyb3roptik Have you had a chance to give it a spin as a sanity check that it functions as you'd expect?

**Comment by gabek** [comment]
Once there's a sign-off that this functionality meets the requirements, a test suite needs to be added. I'm starting on it now, assuming no huge changes will be required.

**Comment by gabek** [comment]
I'm going to add an end-to-end integration test to this next, but I think after that we're relatively covered as far as coverage for functionality.

**Comment by gabek** [comment]
Path prefix: off

Local storage:

image

Remote storage:

image


Path prefix on:

Remote storage:

image

image

Enabled with remote storage and replay functionality:

image

image

image

**Comment by Fyb3roptik** [comment]
Still not getting the correct url here

```
curl http://18.206.39.30:8080/hls/stream.m3u8
#EXTM3U
#EXT-X-VERSION:6
#EXT-X-STREAM-INF:PROGRAM-ID=0,BANDWIDTH=1289024,CODECS="avc1.640028,mp4a.40.2",RESOLUTION=1920x1080
https://media-dev.frontrow.cc/hls/TRsVSqkIg/0/stream.m3u8
```

Should be

```
curl http://18.206.39.30:8080/hls/stream.m3u8
#EXTM3U
#EXT-X-VERSION:6
#EXT-X-STREAM-INF:PROGRAM-ID=0,BANDWIDTH=1289024,CODECS="avc1.640028,mp4a.40.2",RESOLUTION=1920x1080
https://media-dev.frontrow.cc/testing/nick/hls/TRsVSqkIg/0/stream.m3u8
```

**Comment by gabek** [comment]
Are my screenshots representing what you expect?  That's how it's working as it stands. Is your branch up to date?  I'm not sure what could be the issue on your side.

**Comment by gabek** [comment]
- [ ] TODO: Fix tests after yesterday's merge.

**Comment by gabek** [comment]
There seems to be 202 changed files now? That's not right.

**Comment by gabek** [comment]
- [ ] TODO: Currently there's a single slash instead of double slash in absolute URL to the media playlist. Oddly enough it still plays fine, that's why I didn't notice it until now.

**Comment by gabek** [comment]
Now that @Fyb3roptik has tested it out and seems to meet the requirements it would be good to run a handful of long-running tests. Hammering the database's segments table with a ton of segement references, and then query the streams for replays and clips to validate performance. @Fyb3roptik If you want to proactively take a look at the database schema and see if there could be any performance gains that I overlooked with additional indexes and/or query tweaks that would be worthwhile, as well. Owncast hasn't had much need for database performance in the past, since it was used simplisticly and minimally, but this is a big change there.

**Comment by gabek** [comment]
I'm going to leave a stream running all day today when these features enabled to see if there's any side effects or performance implications from tracking so many segments of a long stream.

**Pull request closed without merging**
